# Generated by Django 4.2.3 on 2023-07-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='phone_nr',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
